---
linters:
  enable-all: true
  disable:
    - wsl
    - goerr113
    - nlreturn
    - lll
    - godot
    - exhaustivestruct
    # TODO
    - dupl
    - wrapcheck
    - testpackage
    - stylecheck
    - paralleltest
    - staticcheck
    - gosimple
    - errorlint
    - unparam
    - unconvert
    - prealloc
    - godox
    - nestif
    - gocritic
    - funlen
    - errcheck
    - gci
    - gosec
    - gocognit
    - gocyclo
