---
linters:
  enable-all: true
  disable:
    # WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 

    # WARN [runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'. 
    # WARN [runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  
    # WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref. 
    - maligned
    - interfacer
    - scopelint
    - tagliatelle
    - wsl
    - goerr113
    - nlreturn
    - lll
    - godot
    - exhaustivestruct
    # TODO
    - dupl
    - wrapcheck
    - testpackage
    - godox
    - nestif
    - funlen
    - gocognit
    - gocyclo
