---
linters:
  enable-all: true
  disable:
    - wsl
    - goerr113
    - nlreturn
    - lll
    - godot
    - exhaustivestruct
    # TODO
    - dupl
    - wrapcheck
    - testpackage
    - errorlint
    - unparam
    - godox
    - nestif
    - gocritic
    - funlen
    - gosec
    - gocognit
    - gocyclo
